# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Dotty Matrix"
license = "MIT"
licenselink = "https://github.com/nikolas-schwarz/dotty-matrix/blob/master/LICENSE"
description = ""
homepage = "https://nikolas-schwarz.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Nikolas Schwarz"
  homepage = "https://nikolas-schwarz.github.io/"